version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: image-converter-api:latest
    container_name: image-converter-api-dev
    volumes:
      - .:/app
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    command: >
      sh -c "
        python manage.py runserver 0.0.0.0:8000
      "
    restart: unless-stopped
